{% set name = "natural-keys" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/natural-keys-{{ version }}.tar.gz
  sha256: 67dbfdfd975fe19256c7385aae56b6c7d65d9f595523d1c75703ef91e292da16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2,<5.0
    - html-json-forms >=1.0.0

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import natural_keys"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Enhanced support for natural keys in Django and Django REST Framework.
  home: https://github.com/wq/django-natural-keys
  dev_url: https://github.com/wq/django-natural-keys
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
